name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4.1.7
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v3-beta

    - name: Run build with Gradle Wrapper
      run: ./gradlew build -Ddevelocity.deprecation.captureOrigin=true

    - name: Lint
      run: ./gradlew lint

    - name: Check and report lint results
      uses: hidakatsuya/action-report-android-lint@v1.2.0
      with:
        result-path: 'app/build/reports/lint-results-debug.xml'
        fail-on-warning: false
      
